/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as ApiNodesRouteImport } from './routes/api/nodes'
import { Route as NodesIdRouteImport } from './routes/nodes.$id'
import { Route as ApiNodesIdRouteImport } from './routes/api/nodes/$id'
import { Route as ApiNodesExportRouteImport } from './routes/api/nodes.export'
import { Route as ApiNodesImportRouteImport } from './routes/api/nodes.import'
import { Route as ApiDpNodeIdSplatRouteImport } from './routes/api/dp/$nodeId/$'
import { Route as ApiNodesIdChangesRouteImport } from './routes/api/nodes/$id/changes'
import { Route as ApiNodesIdConfigRouteImport } from './routes/api/nodes/$id/config'
import { Route as ApiNodesIdTestRouteImport } from './routes/api/nodes/$id/test'
import { Route as ApiNodesIdChangesChangeIdRouteImport } from './routes/api/nodes/$id/changes/$changeId'
import { Route as ApiNodesIdChangesChangeIdRevertRouteImport } from './routes/api/nodes/$id/changes/$changeId/revert'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNodesRoute = ApiNodesRouteImport.update({
  id: '/api/nodes',
  path: '/api/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIdRoute = NodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NodesRoute,
} as any)
const ApiNodesIdRoute = ApiNodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiNodesRoute,
} as any)
const ApiNodesExportRoute = ApiNodesExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiNodesRoute,
} as any)
const ApiNodesImportRoute = ApiNodesImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiNodesRoute,
} as any)
const ApiDpNodeIdSplatRoute = ApiDpNodeIdSplatRouteImport.update({
  id: '/api/dp/$nodeId/$',
  path: '/api/dp/$nodeId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNodesIdChangesRoute = ApiNodesIdChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => ApiNodesIdRoute,
} as any)
const ApiNodesIdConfigRoute = ApiNodesIdConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ApiNodesIdRoute,
} as any)
const ApiNodesIdTestRoute = ApiNodesIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiNodesIdRoute,
} as any)
const ApiNodesIdChangesChangeIdRoute =
  ApiNodesIdChangesChangeIdRouteImport.update({
    id: '/$changeId',
    path: '/$changeId',
    getParentRoute: () => ApiNodesIdChangesRoute,
  } as any)
const ApiNodesIdChangesChangeIdRevertRoute =
  ApiNodesIdChangesChangeIdRevertRouteImport.update({
    id: '/revert',
    path: '/revert',
    getParentRoute: () => ApiNodesIdChangesChangeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nodes': typeof NodesRouteWithChildren
  '/api/nodes': typeof ApiNodesRouteWithChildren
  '/nodes/$id': typeof NodesIdRoute
  '/api/nodes/$id': typeof ApiNodesIdRouteWithChildren
  '/api/nodes/export': typeof ApiNodesExportRoute
  '/api/nodes/import': typeof ApiNodesImportRoute
  '/api/dp/$nodeId/$': typeof ApiDpNodeIdSplatRoute
  '/api/nodes/$id/changes': typeof ApiNodesIdChangesRouteWithChildren
  '/api/nodes/$id/config': typeof ApiNodesIdConfigRoute
  '/api/nodes/$id/test': typeof ApiNodesIdTestRoute
  '/api/nodes/$id/changes/$changeId': typeof ApiNodesIdChangesChangeIdRouteWithChildren
  '/api/nodes/$id/changes/$changeId/revert': typeof ApiNodesIdChangesChangeIdRevertRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nodes': typeof NodesRouteWithChildren
  '/api/nodes': typeof ApiNodesRouteWithChildren
  '/nodes/$id': typeof NodesIdRoute
  '/api/nodes/$id': typeof ApiNodesIdRouteWithChildren
  '/api/nodes/export': typeof ApiNodesExportRoute
  '/api/nodes/import': typeof ApiNodesImportRoute
  '/api/dp/$nodeId/$': typeof ApiDpNodeIdSplatRoute
  '/api/nodes/$id/changes': typeof ApiNodesIdChangesRouteWithChildren
  '/api/nodes/$id/config': typeof ApiNodesIdConfigRoute
  '/api/nodes/$id/test': typeof ApiNodesIdTestRoute
  '/api/nodes/$id/changes/$changeId': typeof ApiNodesIdChangesChangeIdRouteWithChildren
  '/api/nodes/$id/changes/$changeId/revert': typeof ApiNodesIdChangesChangeIdRevertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nodes': typeof NodesRouteWithChildren
  '/api/nodes': typeof ApiNodesRouteWithChildren
  '/nodes/$id': typeof NodesIdRoute
  '/api/nodes/$id': typeof ApiNodesIdRouteWithChildren
  '/api/nodes/export': typeof ApiNodesExportRoute
  '/api/nodes/import': typeof ApiNodesImportRoute
  '/api/dp/$nodeId/$': typeof ApiDpNodeIdSplatRoute
  '/api/nodes/$id/changes': typeof ApiNodesIdChangesRouteWithChildren
  '/api/nodes/$id/config': typeof ApiNodesIdConfigRoute
  '/api/nodes/$id/test': typeof ApiNodesIdTestRoute
  '/api/nodes/$id/changes/$changeId': typeof ApiNodesIdChangesChangeIdRouteWithChildren
  '/api/nodes/$id/changes/$changeId/revert': typeof ApiNodesIdChangesChangeIdRevertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nodes'
    | '/api/nodes'
    | '/nodes/$id'
    | '/api/nodes/$id'
    | '/api/nodes/export'
    | '/api/nodes/import'
    | '/api/dp/$nodeId/$'
    | '/api/nodes/$id/changes'
    | '/api/nodes/$id/config'
    | '/api/nodes/$id/test'
    | '/api/nodes/$id/changes/$changeId'
    | '/api/nodes/$id/changes/$changeId/revert'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nodes'
    | '/api/nodes'
    | '/nodes/$id'
    | '/api/nodes/$id'
    | '/api/nodes/export'
    | '/api/nodes/import'
    | '/api/dp/$nodeId/$'
    | '/api/nodes/$id/changes'
    | '/api/nodes/$id/config'
    | '/api/nodes/$id/test'
    | '/api/nodes/$id/changes/$changeId'
    | '/api/nodes/$id/changes/$changeId/revert'
  id:
    | '__root__'
    | '/'
    | '/nodes'
    | '/api/nodes'
    | '/nodes/$id'
    | '/api/nodes/$id'
    | '/api/nodes/export'
    | '/api/nodes/import'
    | '/api/dp/$nodeId/$'
    | '/api/nodes/$id/changes'
    | '/api/nodes/$id/config'
    | '/api/nodes/$id/test'
    | '/api/nodes/$id/changes/$changeId'
    | '/api/nodes/$id/changes/$changeId/revert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NodesRoute: typeof NodesRouteWithChildren
  ApiNodesRoute: typeof ApiNodesRouteWithChildren
  ApiDpNodeIdSplatRoute: typeof ApiDpNodeIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nodes': {
      id: '/api/nodes'
      path: '/api/nodes'
      fullPath: '/api/nodes'
      preLoaderRoute: typeof ApiNodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/$id': {
      id: '/nodes/$id'
      path: '/$id'
      fullPath: '/nodes/$id'
      preLoaderRoute: typeof NodesIdRouteImport
      parentRoute: typeof NodesRoute
    }
    '/api/nodes/$id': {
      id: '/api/nodes/$id'
      path: '/$id'
      fullPath: '/api/nodes/$id'
      preLoaderRoute: typeof ApiNodesIdRouteImport
      parentRoute: typeof ApiNodesRoute
    }
    '/api/nodes/export': {
      id: '/api/nodes/export'
      path: '/export'
      fullPath: '/api/nodes/export'
      preLoaderRoute: typeof ApiNodesExportRouteImport
      parentRoute: typeof ApiNodesRoute
    }
    '/api/nodes/import': {
      id: '/api/nodes/import'
      path: '/import'
      fullPath: '/api/nodes/import'
      preLoaderRoute: typeof ApiNodesImportRouteImport
      parentRoute: typeof ApiNodesRoute
    }
    '/api/dp/$nodeId/$': {
      id: '/api/dp/$nodeId/$'
      path: '/api/dp/$nodeId/$'
      fullPath: '/api/dp/$nodeId/$'
      preLoaderRoute: typeof ApiDpNodeIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nodes/$id/changes': {
      id: '/api/nodes/$id/changes'
      path: '/changes'
      fullPath: '/api/nodes/$id/changes'
      preLoaderRoute: typeof ApiNodesIdChangesRouteImport
      parentRoute: typeof ApiNodesIdRoute
    }
    '/api/nodes/$id/config': {
      id: '/api/nodes/$id/config'
      path: '/config'
      fullPath: '/api/nodes/$id/config'
      preLoaderRoute: typeof ApiNodesIdConfigRouteImport
      parentRoute: typeof ApiNodesIdRoute
    }
    '/api/nodes/$id/test': {
      id: '/api/nodes/$id/test'
      path: '/test'
      fullPath: '/api/nodes/$id/test'
      preLoaderRoute: typeof ApiNodesIdTestRouteImport
      parentRoute: typeof ApiNodesIdRoute
    }
    '/api/nodes/$id/changes/$changeId': {
      id: '/api/nodes/$id/changes/$changeId'
      path: '/$changeId'
      fullPath: '/api/nodes/$id/changes/$changeId'
      preLoaderRoute: typeof ApiNodesIdChangesChangeIdRouteImport
      parentRoute: typeof ApiNodesIdChangesRoute
    }
    '/api/nodes/$id/changes/$changeId/revert': {
      id: '/api/nodes/$id/changes/$changeId/revert'
      path: '/revert'
      fullPath: '/api/nodes/$id/changes/$changeId/revert'
      preLoaderRoute: typeof ApiNodesIdChangesChangeIdRevertRouteImport
      parentRoute: typeof ApiNodesIdChangesChangeIdRoute
    }
  }
}

interface NodesRouteChildren {
  NodesIdRoute: typeof NodesIdRoute
}

const NodesRouteChildren: NodesRouteChildren = {
  NodesIdRoute: NodesIdRoute,
}

const NodesRouteWithChildren = NodesRoute._addFileChildren(NodesRouteChildren)

interface ApiNodesIdChangesChangeIdRouteChildren {
  ApiNodesIdChangesChangeIdRevertRoute: typeof ApiNodesIdChangesChangeIdRevertRoute
}

const ApiNodesIdChangesChangeIdRouteChildren: ApiNodesIdChangesChangeIdRouteChildren =
  {
    ApiNodesIdChangesChangeIdRevertRoute: ApiNodesIdChangesChangeIdRevertRoute,
  }

const ApiNodesIdChangesChangeIdRouteWithChildren =
  ApiNodesIdChangesChangeIdRoute._addFileChildren(
    ApiNodesIdChangesChangeIdRouteChildren,
  )

interface ApiNodesIdChangesRouteChildren {
  ApiNodesIdChangesChangeIdRoute: typeof ApiNodesIdChangesChangeIdRouteWithChildren
}

const ApiNodesIdChangesRouteChildren: ApiNodesIdChangesRouteChildren = {
  ApiNodesIdChangesChangeIdRoute: ApiNodesIdChangesChangeIdRouteWithChildren,
}

const ApiNodesIdChangesRouteWithChildren =
  ApiNodesIdChangesRoute._addFileChildren(ApiNodesIdChangesRouteChildren)

interface ApiNodesIdRouteChildren {
  ApiNodesIdChangesRoute: typeof ApiNodesIdChangesRouteWithChildren
  ApiNodesIdConfigRoute: typeof ApiNodesIdConfigRoute
  ApiNodesIdTestRoute: typeof ApiNodesIdTestRoute
}

const ApiNodesIdRouteChildren: ApiNodesIdRouteChildren = {
  ApiNodesIdChangesRoute: ApiNodesIdChangesRouteWithChildren,
  ApiNodesIdConfigRoute: ApiNodesIdConfigRoute,
  ApiNodesIdTestRoute: ApiNodesIdTestRoute,
}

const ApiNodesIdRouteWithChildren = ApiNodesIdRoute._addFileChildren(
  ApiNodesIdRouteChildren,
)

interface ApiNodesRouteChildren {
  ApiNodesIdRoute: typeof ApiNodesIdRouteWithChildren
  ApiNodesExportRoute: typeof ApiNodesExportRoute
  ApiNodesImportRoute: typeof ApiNodesImportRoute
}

const ApiNodesRouteChildren: ApiNodesRouteChildren = {
  ApiNodesIdRoute: ApiNodesIdRouteWithChildren,
  ApiNodesExportRoute: ApiNodesExportRoute,
  ApiNodesImportRoute: ApiNodesImportRoute,
}

const ApiNodesRouteWithChildren = ApiNodesRoute._addFileChildren(
  ApiNodesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NodesRoute: NodesRouteWithChildren,
  ApiNodesRoute: ApiNodesRouteWithChildren,
  ApiDpNodeIdSplatRoute: ApiDpNodeIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
