/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as ApiNodesRouteImport } from './routes/api/nodes'
import { Route as NodesIdRouteImport } from './routes/nodes.$id'
import { Route as ApiNodesIdRouteImport } from './routes/api/nodes/$id'
import { Route as ApiDpNodeIdSplatRouteImport } from './routes/api/dp/$nodeId/$'
import { Route as ApiNodesIdTestRouteImport } from './routes/api/nodes/$id/test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNodesRoute = ApiNodesRouteImport.update({
  id: '/api/nodes',
  path: '/api/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIdRoute = NodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NodesRoute,
} as any)
const ApiNodesIdRoute = ApiNodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiNodesRoute,
} as any)
const ApiDpNodeIdSplatRoute = ApiDpNodeIdSplatRouteImport.update({
  id: '/api/dp/$nodeId/$',
  path: '/api/dp/$nodeId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNodesIdTestRoute = ApiNodesIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiNodesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nodes': typeof NodesRouteWithChildren
  '/api/nodes': typeof ApiNodesRouteWithChildren
  '/nodes/$id': typeof NodesIdRoute
  '/api/nodes/$id': typeof ApiNodesIdRouteWithChildren
  '/api/dp/$nodeId/$': typeof ApiDpNodeIdSplatRoute
  '/api/nodes/$id/test': typeof ApiNodesIdTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nodes': typeof NodesRouteWithChildren
  '/api/nodes': typeof ApiNodesRouteWithChildren
  '/nodes/$id': typeof NodesIdRoute
  '/api/nodes/$id': typeof ApiNodesIdRouteWithChildren
  '/api/dp/$nodeId/$': typeof ApiDpNodeIdSplatRoute
  '/api/nodes/$id/test': typeof ApiNodesIdTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nodes': typeof NodesRouteWithChildren
  '/api/nodes': typeof ApiNodesRouteWithChildren
  '/nodes/$id': typeof NodesIdRoute
  '/api/nodes/$id': typeof ApiNodesIdRouteWithChildren
  '/api/dp/$nodeId/$': typeof ApiDpNodeIdSplatRoute
  '/api/nodes/$id/test': typeof ApiNodesIdTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nodes'
    | '/api/nodes'
    | '/nodes/$id'
    | '/api/nodes/$id'
    | '/api/dp/$nodeId/$'
    | '/api/nodes/$id/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nodes'
    | '/api/nodes'
    | '/nodes/$id'
    | '/api/nodes/$id'
    | '/api/dp/$nodeId/$'
    | '/api/nodes/$id/test'
  id:
    | '__root__'
    | '/'
    | '/nodes'
    | '/api/nodes'
    | '/nodes/$id'
    | '/api/nodes/$id'
    | '/api/dp/$nodeId/$'
    | '/api/nodes/$id/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NodesRoute: typeof NodesRouteWithChildren
  ApiNodesRoute: typeof ApiNodesRouteWithChildren
  ApiDpNodeIdSplatRoute: typeof ApiDpNodeIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nodes': {
      id: '/api/nodes'
      path: '/api/nodes'
      fullPath: '/api/nodes'
      preLoaderRoute: typeof ApiNodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/$id': {
      id: '/nodes/$id'
      path: '/$id'
      fullPath: '/nodes/$id'
      preLoaderRoute: typeof NodesIdRouteImport
      parentRoute: typeof NodesRoute
    }
    '/api/nodes/$id': {
      id: '/api/nodes/$id'
      path: '/$id'
      fullPath: '/api/nodes/$id'
      preLoaderRoute: typeof ApiNodesIdRouteImport
      parentRoute: typeof ApiNodesRoute
    }
    '/api/dp/$nodeId/$': {
      id: '/api/dp/$nodeId/$'
      path: '/api/dp/$nodeId/$'
      fullPath: '/api/dp/$nodeId/$'
      preLoaderRoute: typeof ApiDpNodeIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nodes/$id/test': {
      id: '/api/nodes/$id/test'
      path: '/test'
      fullPath: '/api/nodes/$id/test'
      preLoaderRoute: typeof ApiNodesIdTestRouteImport
      parentRoute: typeof ApiNodesIdRoute
    }
  }
}

interface NodesRouteChildren {
  NodesIdRoute: typeof NodesIdRoute
}

const NodesRouteChildren: NodesRouteChildren = {
  NodesIdRoute: NodesIdRoute,
}

const NodesRouteWithChildren = NodesRoute._addFileChildren(NodesRouteChildren)

interface ApiNodesIdRouteChildren {
  ApiNodesIdTestRoute: typeof ApiNodesIdTestRoute
}

const ApiNodesIdRouteChildren: ApiNodesIdRouteChildren = {
  ApiNodesIdTestRoute: ApiNodesIdTestRoute,
}

const ApiNodesIdRouteWithChildren = ApiNodesIdRoute._addFileChildren(
  ApiNodesIdRouteChildren,
)

interface ApiNodesRouteChildren {
  ApiNodesIdRoute: typeof ApiNodesIdRouteWithChildren
}

const ApiNodesRouteChildren: ApiNodesRouteChildren = {
  ApiNodesIdRoute: ApiNodesIdRouteWithChildren,
}

const ApiNodesRouteWithChildren = ApiNodesRoute._addFileChildren(
  ApiNodesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NodesRoute: NodesRouteWithChildren,
  ApiNodesRoute: ApiNodesRouteWithChildren,
  ApiDpNodeIdSplatRoute: ApiDpNodeIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
