/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiLogsRouteImport } from './routes/api/logs'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as ApiNodesRouteImport } from './routes/api/nodes'
import { Route as ApiTokensRouteImport } from './routes/api/tokens'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as NodesIndexRouteImport } from './routes/nodes.index'
import { Route as NodesIdRouteImport } from './routes/nodes.$id'
import { Route as ApiAlertsSettingsRouteImport } from './routes/api/alerts/settings'
import { Route as ApiAlertsTestRouteImport } from './routes/api/alerts/test'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthStatusRouteImport } from './routes/api/auth/status'
import { Route as ApiHealthSummaryRouteImport } from './routes/api/health/summary'
import { Route as ApiNodesIdRouteImport } from './routes/api/nodes/$id'
import { Route as ApiNodesDiffRouteImport } from './routes/api/nodes.diff'
import { Route as ApiNodesExportRouteImport } from './routes/api/nodes.export'
import { Route as ApiNodesImportRouteImport } from './routes/api/nodes.import'
import { Route as ApiOpenapiJsonRouteImport } from './routes/api/openapi.json'
import { Route as ApiTokensIdRouteImport } from './routes/api/tokens/$id'
import { Route as ApiUsersUsernameRouteImport } from './routes/api/users/$username'
import { Route as ApiAuthOidcCallbackRouteImport } from './routes/api/auth/oidc/callback'
import { Route as ApiAuthOidcStartRouteImport } from './routes/api/auth/oidc/start'
import { Route as ApiAuthOidcStatusRouteImport } from './routes/api/auth/oidc/status'
import { Route as ApiDpNodeIdSplatRouteImport } from './routes/api/dp/$nodeId/$'
import { Route as ApiNodesIdCertsRouteImport } from './routes/api/nodes/$id/certs'
import { Route as ApiNodesIdChangesRouteImport } from './routes/api/nodes/$id/changes'
import { Route as ApiNodesIdConfigRouteImport } from './routes/api/nodes/$id/config'
import { Route as ApiNodesIdMetricsRouteImport } from './routes/api/nodes/$id/metrics'
import { Route as ApiNodesIdTestRouteImport } from './routes/api/nodes/$id/test'
import { Route as ApiNodesIdUpgradeRouteImport } from './routes/api/nodes/$id/upgrade'
import { Route as ApiNodesIdChangesChangeIdRouteImport } from './routes/api/nodes/$id/changes/$changeId'
import { Route as ApiNodesIdChangesChangeIdRevertRouteImport } from './routes/api/nodes/$id/changes/$changeId/revert'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api/logs',
  path: '/api/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNodesRoute = ApiNodesRouteImport.update({
  id: '/api/nodes',
  path: '/api/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensRoute = ApiTokensRouteImport.update({
  id: '/api/tokens',
  path: '/api/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NodesRoute,
} as any)
const NodesIdRoute = NodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NodesRoute,
} as any)
const ApiAlertsSettingsRoute = ApiAlertsSettingsRouteImport.update({
  id: '/api/alerts/settings',
  path: '/api/alerts/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsTestRoute = ApiAlertsTestRouteImport.update({
  id: '/api/alerts/test',
  path: '/api/alerts/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStatusRoute = ApiAuthStatusRouteImport.update({
  id: '/api/auth/status',
  path: '/api/auth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthSummaryRoute = ApiHealthSummaryRouteImport.update({
  id: '/api/health/summary',
  path: '/api/health/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNodesIdRoute = ApiNodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiNodesRoute,
} as any)
const ApiNodesDiffRoute = ApiNodesDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => ApiNodesRoute,
} as any)
const ApiNodesExportRoute = ApiNodesExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiNodesRoute,
} as any)
const ApiNodesImportRoute = ApiNodesImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiNodesRoute,
} as any)
const ApiOpenapiJsonRoute = ApiOpenapiJsonRouteImport.update({
  id: '/api/openapi/json',
  path: '/api/openapi/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensIdRoute = ApiTokensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTokensRoute,
} as any)
const ApiUsersUsernameRoute = ApiUsersUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiAuthOidcCallbackRoute = ApiAuthOidcCallbackRouteImport.update({
  id: '/api/auth/oidc/callback',
  path: '/api/auth/oidc/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOidcStartRoute = ApiAuthOidcStartRouteImport.update({
  id: '/api/auth/oidc/start',
  path: '/api/auth/oidc/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOidcStatusRoute = ApiAuthOidcStatusRouteImport.update({
  id: '/api/auth/oidc/status',
  path: '/api/auth/oidc/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDpNodeIdSplatRoute = ApiDpNodeIdSplatRouteImport.update({
  id: '/api/dp/$nodeId/$',
  path: '/api/dp/$nodeId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNodesIdCertsRoute = ApiNodesIdCertsRouteImport.update({
  id: '/certs',
  path: '/certs',
  getParentRoute: () => ApiNodesIdRoute,
} as any)
const ApiNodesIdChangesRoute = ApiNodesIdChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => ApiNodesIdRoute,
} as any)
const ApiNodesIdConfigRoute = ApiNodesIdConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ApiNodesIdRoute,
} as any)
const ApiNodesIdMetricsRoute = ApiNodesIdMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => ApiNodesIdRoute,
} as any)
const ApiNodesIdTestRoute = ApiNodesIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiNodesIdRoute,
} as any)
const ApiNodesIdUpgradeRoute = ApiNodesIdUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => ApiNodesIdRoute,
} as any)
const ApiNodesIdChangesChangeIdRoute =
  ApiNodesIdChangesChangeIdRouteImport.update({
    id: '/$changeId',
    path: '/$changeId',
    getParentRoute: () => ApiNodesIdChangesRoute,
  } as any)
const ApiNodesIdChangesChangeIdRevertRoute =
  ApiNodesIdChangesChangeIdRevertRouteImport.update({
    id: '/revert',
    path: '/revert',
    getParentRoute: () => ApiNodesIdChangesChangeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nodes': typeof NodesRouteWithChildren
  '/tokens': typeof TokensRoute
  '/users': typeof UsersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/nodes': typeof ApiNodesRouteWithChildren
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/nodes/$id': typeof NodesIdRoute
  '/nodes/': typeof NodesIndexRoute
  '/api/alerts/settings': typeof ApiAlertsSettingsRoute
  '/api/alerts/test': typeof ApiAlertsTestRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/health/summary': typeof ApiHealthSummaryRoute
  '/api/nodes/$id': typeof ApiNodesIdRouteWithChildren
  '/api/nodes/diff': typeof ApiNodesDiffRoute
  '/api/nodes/export': typeof ApiNodesExportRoute
  '/api/nodes/import': typeof ApiNodesImportRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/tokens/$id': typeof ApiTokensIdRoute
  '/api/users/$username': typeof ApiUsersUsernameRoute
  '/api/auth/oidc/callback': typeof ApiAuthOidcCallbackRoute
  '/api/auth/oidc/start': typeof ApiAuthOidcStartRoute
  '/api/auth/oidc/status': typeof ApiAuthOidcStatusRoute
  '/api/dp/$nodeId/$': typeof ApiDpNodeIdSplatRoute
  '/api/nodes/$id/certs': typeof ApiNodesIdCertsRoute
  '/api/nodes/$id/changes': typeof ApiNodesIdChangesRouteWithChildren
  '/api/nodes/$id/config': typeof ApiNodesIdConfigRoute
  '/api/nodes/$id/metrics': typeof ApiNodesIdMetricsRoute
  '/api/nodes/$id/test': typeof ApiNodesIdTestRoute
  '/api/nodes/$id/upgrade': typeof ApiNodesIdUpgradeRoute
  '/api/nodes/$id/changes/$changeId': typeof ApiNodesIdChangesChangeIdRouteWithChildren
  '/api/nodes/$id/changes/$changeId/revert': typeof ApiNodesIdChangesChangeIdRevertRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tokens': typeof TokensRoute
  '/users': typeof UsersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/nodes': typeof ApiNodesRouteWithChildren
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/nodes/$id': typeof NodesIdRoute
  '/nodes': typeof NodesIndexRoute
  '/api/alerts/settings': typeof ApiAlertsSettingsRoute
  '/api/alerts/test': typeof ApiAlertsTestRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/health/summary': typeof ApiHealthSummaryRoute
  '/api/nodes/$id': typeof ApiNodesIdRouteWithChildren
  '/api/nodes/diff': typeof ApiNodesDiffRoute
  '/api/nodes/export': typeof ApiNodesExportRoute
  '/api/nodes/import': typeof ApiNodesImportRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/tokens/$id': typeof ApiTokensIdRoute
  '/api/users/$username': typeof ApiUsersUsernameRoute
  '/api/auth/oidc/callback': typeof ApiAuthOidcCallbackRoute
  '/api/auth/oidc/start': typeof ApiAuthOidcStartRoute
  '/api/auth/oidc/status': typeof ApiAuthOidcStatusRoute
  '/api/dp/$nodeId/$': typeof ApiDpNodeIdSplatRoute
  '/api/nodes/$id/certs': typeof ApiNodesIdCertsRoute
  '/api/nodes/$id/changes': typeof ApiNodesIdChangesRouteWithChildren
  '/api/nodes/$id/config': typeof ApiNodesIdConfigRoute
  '/api/nodes/$id/metrics': typeof ApiNodesIdMetricsRoute
  '/api/nodes/$id/test': typeof ApiNodesIdTestRoute
  '/api/nodes/$id/upgrade': typeof ApiNodesIdUpgradeRoute
  '/api/nodes/$id/changes/$changeId': typeof ApiNodesIdChangesChangeIdRouteWithChildren
  '/api/nodes/$id/changes/$changeId/revert': typeof ApiNodesIdChangesChangeIdRevertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nodes': typeof NodesRouteWithChildren
  '/tokens': typeof TokensRoute
  '/users': typeof UsersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/nodes': typeof ApiNodesRouteWithChildren
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/nodes/$id': typeof NodesIdRoute
  '/nodes/': typeof NodesIndexRoute
  '/api/alerts/settings': typeof ApiAlertsSettingsRoute
  '/api/alerts/test': typeof ApiAlertsTestRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/health/summary': typeof ApiHealthSummaryRoute
  '/api/nodes/$id': typeof ApiNodesIdRouteWithChildren
  '/api/nodes/diff': typeof ApiNodesDiffRoute
  '/api/nodes/export': typeof ApiNodesExportRoute
  '/api/nodes/import': typeof ApiNodesImportRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/tokens/$id': typeof ApiTokensIdRoute
  '/api/users/$username': typeof ApiUsersUsernameRoute
  '/api/auth/oidc/callback': typeof ApiAuthOidcCallbackRoute
  '/api/auth/oidc/start': typeof ApiAuthOidcStartRoute
  '/api/auth/oidc/status': typeof ApiAuthOidcStatusRoute
  '/api/dp/$nodeId/$': typeof ApiDpNodeIdSplatRoute
  '/api/nodes/$id/certs': typeof ApiNodesIdCertsRoute
  '/api/nodes/$id/changes': typeof ApiNodesIdChangesRouteWithChildren
  '/api/nodes/$id/config': typeof ApiNodesIdConfigRoute
  '/api/nodes/$id/metrics': typeof ApiNodesIdMetricsRoute
  '/api/nodes/$id/test': typeof ApiNodesIdTestRoute
  '/api/nodes/$id/upgrade': typeof ApiNodesIdUpgradeRoute
  '/api/nodes/$id/changes/$changeId': typeof ApiNodesIdChangesChangeIdRouteWithChildren
  '/api/nodes/$id/changes/$changeId/revert': typeof ApiNodesIdChangesChangeIdRevertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/nodes'
    | '/tokens'
    | '/users'
    | '/api/events'
    | '/api/logs'
    | '/api/metrics'
    | '/api/nodes'
    | '/api/tokens'
    | '/api/users'
    | '/nodes/$id'
    | '/nodes/'
    | '/api/alerts/settings'
    | '/api/alerts/test'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/status'
    | '/api/health/summary'
    | '/api/nodes/$id'
    | '/api/nodes/diff'
    | '/api/nodes/export'
    | '/api/nodes/import'
    | '/api/openapi/json'
    | '/api/tokens/$id'
    | '/api/users/$username'
    | '/api/auth/oidc/callback'
    | '/api/auth/oidc/start'
    | '/api/auth/oidc/status'
    | '/api/dp/$nodeId/$'
    | '/api/nodes/$id/certs'
    | '/api/nodes/$id/changes'
    | '/api/nodes/$id/config'
    | '/api/nodes/$id/metrics'
    | '/api/nodes/$id/test'
    | '/api/nodes/$id/upgrade'
    | '/api/nodes/$id/changes/$changeId'
    | '/api/nodes/$id/changes/$changeId/revert'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tokens'
    | '/users'
    | '/api/events'
    | '/api/logs'
    | '/api/metrics'
    | '/api/nodes'
    | '/api/tokens'
    | '/api/users'
    | '/nodes/$id'
    | '/nodes'
    | '/api/alerts/settings'
    | '/api/alerts/test'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/status'
    | '/api/health/summary'
    | '/api/nodes/$id'
    | '/api/nodes/diff'
    | '/api/nodes/export'
    | '/api/nodes/import'
    | '/api/openapi/json'
    | '/api/tokens/$id'
    | '/api/users/$username'
    | '/api/auth/oidc/callback'
    | '/api/auth/oidc/start'
    | '/api/auth/oidc/status'
    | '/api/dp/$nodeId/$'
    | '/api/nodes/$id/certs'
    | '/api/nodes/$id/changes'
    | '/api/nodes/$id/config'
    | '/api/nodes/$id/metrics'
    | '/api/nodes/$id/test'
    | '/api/nodes/$id/upgrade'
    | '/api/nodes/$id/changes/$changeId'
    | '/api/nodes/$id/changes/$changeId/revert'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/nodes'
    | '/tokens'
    | '/users'
    | '/api/events'
    | '/api/logs'
    | '/api/metrics'
    | '/api/nodes'
    | '/api/tokens'
    | '/api/users'
    | '/nodes/$id'
    | '/nodes/'
    | '/api/alerts/settings'
    | '/api/alerts/test'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/status'
    | '/api/health/summary'
    | '/api/nodes/$id'
    | '/api/nodes/diff'
    | '/api/nodes/export'
    | '/api/nodes/import'
    | '/api/openapi/json'
    | '/api/tokens/$id'
    | '/api/users/$username'
    | '/api/auth/oidc/callback'
    | '/api/auth/oidc/start'
    | '/api/auth/oidc/status'
    | '/api/dp/$nodeId/$'
    | '/api/nodes/$id/certs'
    | '/api/nodes/$id/changes'
    | '/api/nodes/$id/config'
    | '/api/nodes/$id/metrics'
    | '/api/nodes/$id/test'
    | '/api/nodes/$id/upgrade'
    | '/api/nodes/$id/changes/$changeId'
    | '/api/nodes/$id/changes/$changeId/revert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NodesRoute: typeof NodesRouteWithChildren
  TokensRoute: typeof TokensRoute
  UsersRoute: typeof UsersRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiLogsRoute: typeof ApiLogsRoute
  ApiMetricsRoute: typeof ApiMetricsRoute
  ApiNodesRoute: typeof ApiNodesRouteWithChildren
  ApiTokensRoute: typeof ApiTokensRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAlertsSettingsRoute: typeof ApiAlertsSettingsRoute
  ApiAlertsTestRoute: typeof ApiAlertsTestRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthStatusRoute: typeof ApiAuthStatusRoute
  ApiHealthSummaryRoute: typeof ApiHealthSummaryRoute
  ApiOpenapiJsonRoute: typeof ApiOpenapiJsonRoute
  ApiAuthOidcCallbackRoute: typeof ApiAuthOidcCallbackRoute
  ApiAuthOidcStartRoute: typeof ApiAuthOidcStartRoute
  ApiAuthOidcStatusRoute: typeof ApiAuthOidcStatusRoute
  ApiDpNodeIdSplatRoute: typeof ApiDpNodeIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logs': {
      id: '/api/logs'
      path: '/api/logs'
      fullPath: '/api/logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nodes': {
      id: '/api/nodes'
      path: '/api/nodes'
      fullPath: '/api/nodes'
      preLoaderRoute: typeof ApiNodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens': {
      id: '/api/tokens'
      path: '/api/tokens'
      fullPath: '/api/tokens'
      preLoaderRoute: typeof ApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof NodesRoute
    }
    '/nodes/$id': {
      id: '/nodes/$id'
      path: '/$id'
      fullPath: '/nodes/$id'
      preLoaderRoute: typeof NodesIdRouteImport
      parentRoute: typeof NodesRoute
    }
    '/api/alerts/settings': {
      id: '/api/alerts/settings'
      path: '/api/alerts/settings'
      fullPath: '/api/alerts/settings'
      preLoaderRoute: typeof ApiAlertsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/test': {
      id: '/api/alerts/test'
      path: '/api/alerts/test'
      fullPath: '/api/alerts/test'
      preLoaderRoute: typeof ApiAlertsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/status': {
      id: '/api/auth/status'
      path: '/api/auth/status'
      fullPath: '/api/auth/status'
      preLoaderRoute: typeof ApiAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/summary': {
      id: '/api/health/summary'
      path: '/api/health/summary'
      fullPath: '/api/health/summary'
      preLoaderRoute: typeof ApiHealthSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nodes/$id': {
      id: '/api/nodes/$id'
      path: '/$id'
      fullPath: '/api/nodes/$id'
      preLoaderRoute: typeof ApiNodesIdRouteImport
      parentRoute: typeof ApiNodesRoute
    }
    '/api/nodes/diff': {
      id: '/api/nodes/diff'
      path: '/diff'
      fullPath: '/api/nodes/diff'
      preLoaderRoute: typeof ApiNodesDiffRouteImport
      parentRoute: typeof ApiNodesRoute
    }
    '/api/nodes/export': {
      id: '/api/nodes/export'
      path: '/export'
      fullPath: '/api/nodes/export'
      preLoaderRoute: typeof ApiNodesExportRouteImport
      parentRoute: typeof ApiNodesRoute
    }
    '/api/nodes/import': {
      id: '/api/nodes/import'
      path: '/import'
      fullPath: '/api/nodes/import'
      preLoaderRoute: typeof ApiNodesImportRouteImport
      parentRoute: typeof ApiNodesRoute
    }
    '/api/openapi/json': {
      id: '/api/openapi/json'
      path: '/api/openapi/json'
      fullPath: '/api/openapi/json'
      preLoaderRoute: typeof ApiOpenapiJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens/$id': {
      id: '/api/tokens/$id'
      path: '/$id'
      fullPath: '/api/tokens/$id'
      preLoaderRoute: typeof ApiTokensIdRouteImport
      parentRoute: typeof ApiTokensRoute
    }
    '/api/users/$username': {
      id: '/api/users/$username'
      path: '/$username'
      fullPath: '/api/users/$username'
      preLoaderRoute: typeof ApiUsersUsernameRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/auth/oidc/callback': {
      id: '/api/auth/oidc/callback'
      path: '/api/auth/oidc/callback'
      fullPath: '/api/auth/oidc/callback'
      preLoaderRoute: typeof ApiAuthOidcCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/oidc/start': {
      id: '/api/auth/oidc/start'
      path: '/api/auth/oidc/start'
      fullPath: '/api/auth/oidc/start'
      preLoaderRoute: typeof ApiAuthOidcStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/oidc/status': {
      id: '/api/auth/oidc/status'
      path: '/api/auth/oidc/status'
      fullPath: '/api/auth/oidc/status'
      preLoaderRoute: typeof ApiAuthOidcStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dp/$nodeId/$': {
      id: '/api/dp/$nodeId/$'
      path: '/api/dp/$nodeId/$'
      fullPath: '/api/dp/$nodeId/$'
      preLoaderRoute: typeof ApiDpNodeIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nodes/$id/certs': {
      id: '/api/nodes/$id/certs'
      path: '/certs'
      fullPath: '/api/nodes/$id/certs'
      preLoaderRoute: typeof ApiNodesIdCertsRouteImport
      parentRoute: typeof ApiNodesIdRoute
    }
    '/api/nodes/$id/changes': {
      id: '/api/nodes/$id/changes'
      path: '/changes'
      fullPath: '/api/nodes/$id/changes'
      preLoaderRoute: typeof ApiNodesIdChangesRouteImport
      parentRoute: typeof ApiNodesIdRoute
    }
    '/api/nodes/$id/config': {
      id: '/api/nodes/$id/config'
      path: '/config'
      fullPath: '/api/nodes/$id/config'
      preLoaderRoute: typeof ApiNodesIdConfigRouteImport
      parentRoute: typeof ApiNodesIdRoute
    }
    '/api/nodes/$id/metrics': {
      id: '/api/nodes/$id/metrics'
      path: '/metrics'
      fullPath: '/api/nodes/$id/metrics'
      preLoaderRoute: typeof ApiNodesIdMetricsRouteImport
      parentRoute: typeof ApiNodesIdRoute
    }
    '/api/nodes/$id/test': {
      id: '/api/nodes/$id/test'
      path: '/test'
      fullPath: '/api/nodes/$id/test'
      preLoaderRoute: typeof ApiNodesIdTestRouteImport
      parentRoute: typeof ApiNodesIdRoute
    }
    '/api/nodes/$id/upgrade': {
      id: '/api/nodes/$id/upgrade'
      path: '/upgrade'
      fullPath: '/api/nodes/$id/upgrade'
      preLoaderRoute: typeof ApiNodesIdUpgradeRouteImport
      parentRoute: typeof ApiNodesIdRoute
    }
    '/api/nodes/$id/changes/$changeId': {
      id: '/api/nodes/$id/changes/$changeId'
      path: '/$changeId'
      fullPath: '/api/nodes/$id/changes/$changeId'
      preLoaderRoute: typeof ApiNodesIdChangesChangeIdRouteImport
      parentRoute: typeof ApiNodesIdChangesRoute
    }
    '/api/nodes/$id/changes/$changeId/revert': {
      id: '/api/nodes/$id/changes/$changeId/revert'
      path: '/revert'
      fullPath: '/api/nodes/$id/changes/$changeId/revert'
      preLoaderRoute: typeof ApiNodesIdChangesChangeIdRevertRouteImport
      parentRoute: typeof ApiNodesIdChangesChangeIdRoute
    }
  }
}

interface NodesRouteChildren {
  NodesIdRoute: typeof NodesIdRoute
  NodesIndexRoute: typeof NodesIndexRoute
}

const NodesRouteChildren: NodesRouteChildren = {
  NodesIdRoute: NodesIdRoute,
  NodesIndexRoute: NodesIndexRoute,
}

const NodesRouteWithChildren = NodesRoute._addFileChildren(NodesRouteChildren)

interface ApiNodesIdChangesChangeIdRouteChildren {
  ApiNodesIdChangesChangeIdRevertRoute: typeof ApiNodesIdChangesChangeIdRevertRoute
}

const ApiNodesIdChangesChangeIdRouteChildren: ApiNodesIdChangesChangeIdRouteChildren =
  {
    ApiNodesIdChangesChangeIdRevertRoute: ApiNodesIdChangesChangeIdRevertRoute,
  }

const ApiNodesIdChangesChangeIdRouteWithChildren =
  ApiNodesIdChangesChangeIdRoute._addFileChildren(
    ApiNodesIdChangesChangeIdRouteChildren,
  )

interface ApiNodesIdChangesRouteChildren {
  ApiNodesIdChangesChangeIdRoute: typeof ApiNodesIdChangesChangeIdRouteWithChildren
}

const ApiNodesIdChangesRouteChildren: ApiNodesIdChangesRouteChildren = {
  ApiNodesIdChangesChangeIdRoute: ApiNodesIdChangesChangeIdRouteWithChildren,
}

const ApiNodesIdChangesRouteWithChildren =
  ApiNodesIdChangesRoute._addFileChildren(ApiNodesIdChangesRouteChildren)

interface ApiNodesIdRouteChildren {
  ApiNodesIdCertsRoute: typeof ApiNodesIdCertsRoute
  ApiNodesIdChangesRoute: typeof ApiNodesIdChangesRouteWithChildren
  ApiNodesIdConfigRoute: typeof ApiNodesIdConfigRoute
  ApiNodesIdMetricsRoute: typeof ApiNodesIdMetricsRoute
  ApiNodesIdTestRoute: typeof ApiNodesIdTestRoute
  ApiNodesIdUpgradeRoute: typeof ApiNodesIdUpgradeRoute
}

const ApiNodesIdRouteChildren: ApiNodesIdRouteChildren = {
  ApiNodesIdCertsRoute: ApiNodesIdCertsRoute,
  ApiNodesIdChangesRoute: ApiNodesIdChangesRouteWithChildren,
  ApiNodesIdConfigRoute: ApiNodesIdConfigRoute,
  ApiNodesIdMetricsRoute: ApiNodesIdMetricsRoute,
  ApiNodesIdTestRoute: ApiNodesIdTestRoute,
  ApiNodesIdUpgradeRoute: ApiNodesIdUpgradeRoute,
}

const ApiNodesIdRouteWithChildren = ApiNodesIdRoute._addFileChildren(
  ApiNodesIdRouteChildren,
)

interface ApiNodesRouteChildren {
  ApiNodesIdRoute: typeof ApiNodesIdRouteWithChildren
  ApiNodesDiffRoute: typeof ApiNodesDiffRoute
  ApiNodesExportRoute: typeof ApiNodesExportRoute
  ApiNodesImportRoute: typeof ApiNodesImportRoute
}

const ApiNodesRouteChildren: ApiNodesRouteChildren = {
  ApiNodesIdRoute: ApiNodesIdRouteWithChildren,
  ApiNodesDiffRoute: ApiNodesDiffRoute,
  ApiNodesExportRoute: ApiNodesExportRoute,
  ApiNodesImportRoute: ApiNodesImportRoute,
}

const ApiNodesRouteWithChildren = ApiNodesRoute._addFileChildren(
  ApiNodesRouteChildren,
)

interface ApiTokensRouteChildren {
  ApiTokensIdRoute: typeof ApiTokensIdRoute
}

const ApiTokensRouteChildren: ApiTokensRouteChildren = {
  ApiTokensIdRoute: ApiTokensIdRoute,
}

const ApiTokensRouteWithChildren = ApiTokensRoute._addFileChildren(
  ApiTokensRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersUsernameRoute: typeof ApiUsersUsernameRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUsernameRoute: ApiUsersUsernameRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NodesRoute: NodesRouteWithChildren,
  TokensRoute: TokensRoute,
  UsersRoute: UsersRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiLogsRoute: ApiLogsRoute,
  ApiMetricsRoute: ApiMetricsRoute,
  ApiNodesRoute: ApiNodesRouteWithChildren,
  ApiTokensRoute: ApiTokensRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAlertsSettingsRoute: ApiAlertsSettingsRoute,
  ApiAlertsTestRoute: ApiAlertsTestRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthStatusRoute: ApiAuthStatusRoute,
  ApiHealthSummaryRoute: ApiHealthSummaryRoute,
  ApiOpenapiJsonRoute: ApiOpenapiJsonRoute,
  ApiAuthOidcCallbackRoute: ApiAuthOidcCallbackRoute,
  ApiAuthOidcStartRoute: ApiAuthOidcStartRoute,
  ApiAuthOidcStatusRoute: ApiAuthOidcStatusRoute,
  ApiDpNodeIdSplatRoute: ApiDpNodeIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
